name: build and test

on:
  push:
    branches:
      - main
      - dev
      - 'feat/**'
  pull_request:
    branches:
        - main
        - dev
    types:
      - closed


jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

  notify:
    name: Send Notification
    needs: test # job
    runs-on: ubuntu-latest

    steps:
      - name: Notify via Slack
        uses: rtCamp/action-slack-notify@v2
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      if: always()