on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: action-slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: "#git-test-noti"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_MESSAGE: "test_ci repository 브랜치에 변경 사항이 적용되었습니다."
        if: always() # Pick up events even if the job fails or is canceled.